PRG=ConcurrentLFSVTest.exe

GCC=g++
GCCFLAGS=-O3 -Wall -Wextra -std=c++17 -latomic -mcx16

OBJECTS=driver.o GarbageRemover.o lfsv.o MemoryBank.o
SOURCES=driver.cpp GarbageRemover.cpp lfsv.cpp MemoryBank.cpp

all: $(PRG)

$(PRG): $(OBJECTS)
	$(GCC) -o $@ $^ $(GCCFLAGS) -pthread

%.o: %.cpp
	$(GCC) $(GCCFLAGS) -c $< -o $@

memcheck: $(PRG)
	drmemory -- $(PRG)

clean:
	rm -f *.exe *.o *.obj $(PRG)

.PHONY: all memcheck clean
