CXX=clang++
CXXFLAGS=-Wall -Wextra -std=c++11 -mcx16
OBJECTS=driver.o GarbageRemover.o LFSV.o MemoryBank.o
EXECUTABLE=ConcurrentLFSVTest

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)

memcheck: $(EXECUTABLE)
	valgrind --leak-check=full ./$(EXECUTABLE)
